### ISSUE TITLE
How do I send a pdf file ?

### ISSUE THREAD

**Issue by Lenz60** [nizarfadlan/baileys-api#11]
How do I attach pdf file to the chat message  instead of its link ?

**Comment by Fajar-G** [comment]
try this

{
    "jid": "xxxxxxxxxxx@s.whatsapp.net",
    "type": "number",
    "message": {
        "document": { 
            "url": "https://example.com/file.pdf" 
        }, 
        "mimetype": "application/pdf",
        "caption": "bla bla bla"
    }
}

**Comment by Lenz60** [comment]
> try this
> 
> ```
> {
>     "jid": "xxxxxxxxxxx@s.whatsapp.net",
>     "type": "number",
>     "message": {
>         "document": { 
>             "url": "https://example.com/file.pdf" 
>         }, 
>         "mimetype": "application/pdf",
>         "caption": "bla bla bla"
>     }
> }
> ```

Great!, its working, Thankss
