### ISSUE TITLE
how send to specific number ? 

### ISSUE THREAD

**Issue by ahmadsukabul** [nizarfadlan/baileys-api#12]
<img width="624" alt="Screenshot 2024-09-07 at 16 54 17" src="https://github.com/user-attachments/assets/a405467d-5ae6-44cc-9855-fd286dd24864">

iam looking how send to specific number, but i just only found this. pelase help me

**Comment by nizarfadlan** [comment]
You can check the documentation for sending to a number

https://www.postman.com/supply-meteorologist-96562615/baileys/documentation/9yuuao2/baileys-api-v2-0-0?entity=request-14456337-84543cb5-9782-4d4d-8a10-f4488bbdf35d

for the contents of the message object and options, you can check the official baileys documentation.

Sorry for not being able to provide swagger documentation that is easily accessible, maybe if there is time I can make it.
