### ISSUE TITLE
unable to start [Temporary Solved]

### ISSUE THREAD

**Issue by taufanbudiman** [nizarfadlan/baileys-api#20]
<img width="1595" alt="image" src="https://github.com/user-attachments/assets/106b9fe3-87dc-4336-9821-98dd10cdd82b">

node version 20.18.0
baileys version 2.0.0

i got an error.. anyone can help me?

**Comment by shedenk** [comment]
I'm like that too

**Comment by taufanbudiman** [comment]
not solved until now? @shedenk 
or are there any other alternatives that you might know?

**Comment by taufanbudiman** [comment]
@shedenk 

comment in service.ts
```ts
static getSessionStatus(session: Session) {
    // const state = ["CONNECTING", "CONNECTED", "DISCONNECTING", "DISCONNECTED"];
    // let status = state[(session.ws as WebSocketType).readyState];
    // status = session.user ? "AUTHENTICATED" : status;
    // return session.waStatus !== WAStatus.Unknown ? session.waStatus : status.toLowerCase();
    return session.waStatus;
 }
```

and in message.ts i comment `deleteMessageForMe` because is not used

**Comment by shedenk** [comment]
now it's working, thank you
